name: asm2nockma
version: 1.0
license: GPL-3.0-only
copyright: Jan Mas Rovira
maintainer: Jan Mas Rovira
author:
  [
    Jan Mas Rovira,
  ]
tested-with: ghc == 9.4.5
description: Compiling simple asm language to nockma

dependencies:
  - base == 4.17.*
  - containers == 0.6.*
  - extra == 1.7.*
  - hashable == 1.4.*
  - megaparsec == 9.3.*
  - microlens-platform == 0.4.*
  - parser-combinators == 1.3.*
  - polysemy == 1.9.*
  # - polysemy-plugin == 0.4.*
  - safe == 0.3.*
  - text == 2.0.*
  - transformers == 0.5.*
  - unordered-containers == 0.2.*
  - juvix

ghc-options:
  # Warnings
  - -Weverything
  - -Wno-all-missed-specialisations
  - -Wno-missing-export-lists
  - -Wno-missing-import-lists
  - -Wno-missing-kind-signatures
  - -Wno-missing-safe-haskell-mode
  - -Wno-safe
  - -Wno-unsafe
  - -Wno-unused-packages
  # HIE Support
  - -fhide-source-paths
  - -fwrite-ide-info -hiedir=.hie
  # Polysemy Support
  - -O2 -flate-specialise -fspecialise-aggressively

default-extensions:
  - ApplicativeDo
  - DataKinds
  - DerivingStrategies
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiWayIf
  - NoFieldSelectors
  - NoImplicitPrelude
  - OverloadedStrings
  - RecordWildCards
  - TemplateHaskell
  - TypeFamilyDependencies

library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

executables:
  asm2nockma:
    main: Main.hs
    source-dirs: app
    dependencies:
      - asm2nockma
    verbatim:
      default-language: GHC2021
